apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: jianping-shu-next-js-app
  app.kubernetes.io/instance: jianping-shu-next-js-app-instance
  app.kubernetes.io/name: jianping-shu-next-js-app
images:
- name: quay.io/upslope/express-sample-app
  newName: quay.io/jian_ping_shu/next_js
  newTag: 0dfae57a39b29cb61eee4b484c470cc13725f20e
