apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: tekton-squad-1-project-app
  app.kubernetes.io/instance: tekton-squad-1-project-app-instance
  app.kubernetes.io/name: tekton-squad-1-project-app
images:
- name: quay.io/upslope/express-sample-app
  newName: quay.io/jian_ping_shu/next_js
  newTag: 5916845210f0b838403d574d85d419bb8a3177a3
